{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Untitled0.ipynb","provenance":[],"authorship_tag":"ABX9TyObtEhrBw4L/cYMJn+zLa6m"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","metadata":{"id":"JJV8iPVZzTva","colab":{"base_uri":"https://localhost:8080/","height":1000},"outputId":"7d281761-6b46-4862-8f22-8b335344e363"},"source":["print('NOTE: Intentionally crashing session to use the newly installed library.\\n')\n","\n","!pip uninstall -y pyarrow\n","!pip install ray[debug]==0.7.5\n","!pip install -U ipykernel\n","!pip install modin[dask]\n","!pip install modin[ray]\n","\n","# A hack to force the runtime to restart, needed to include the above dependencies.\n","import os\n","os._exit(0)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["NOTE: Intentionally crashing session to use the newly installed library.\n","\n","Found existing installation: pyarrow 3.0.0\n","Uninstalling pyarrow-3.0.0:\n","  Successfully uninstalled pyarrow-3.0.0\n","Collecting ray[debug]==0.7.5\n","  Downloading ray-0.7.5-cp37-cp37m-manylinux1_x86_64.whl (74.9 MB)\n","\u001b[K     |████████████████████████████████| 74.9 MB 21 kB/s \n","\u001b[?25hRequirement already satisfied: six>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ray[debug]==0.7.5) (1.15.0)\n","Collecting redis>=3.3.2\n","  Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)\n","\u001b[K     |████████████████████████████████| 72 kB 495 kB/s \n","\u001b[?25hRequirement already satisfied: numpy>=1.14 in /usr/local/lib/python3.7/dist-packages (from ray[debug]==0.7.5) (1.19.5)\n","Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from ray[debug]==0.7.5) (3.6.4)\n","Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from ray[debug]==0.7.5) (3.13)\n","Collecting colorama\n","  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)\n","Collecting funcsigs\n","  Downloading funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)\n","Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from ray[debug]==0.7.5) (7.1.2)\n","Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from ray[debug]==0.7.5) (3.0.12)\n","Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/dist-packages (from ray[debug]==0.7.5) (2.6.0)\n","Requirement already satisfied: protobuf>=3.8.0 in /usr/local/lib/python3.7/dist-packages (from ray[debug]==0.7.5) (3.17.3)\n","Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from ray[debug]==0.7.5) (5.4.8)\n","Collecting setproctitle\n","  Downloading setproctitle-1.2.2-cp37-cp37m-manylinux1_x86_64.whl (36 kB)\n","Collecting py-spy\n","  Downloading py_spy-0.3.8-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.1 MB)\n","\u001b[K     |████████████████████████████████| 3.1 MB 39.8 MB/s \n","\u001b[?25hRequirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->ray[debug]==0.7.5) (0.7.1)\n","Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from pytest->ray[debug]==0.7.5) (21.2.0)\n","Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->ray[debug]==0.7.5) (8.8.0)\n","Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pytest->ray[debug]==0.7.5) (57.4.0)\n","Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->ray[debug]==0.7.5) (1.10.0)\n","Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->ray[debug]==0.7.5) (1.4.0)\n","Installing collected packages: redis, funcsigs, colorama, setproctitle, ray, py-spy\n","Successfully installed colorama-0.4.4 funcsigs-1.0.2 py-spy-0.3.8 ray-0.7.5 redis-3.5.3 setproctitle-1.2.2\n","Requirement already satisfied: ipykernel in /usr/local/lib/python3.7/dist-packages (4.10.1)\n","Collecting ipykernel\n","  Downloading ipykernel-6.2.0-py3-none-any.whl (122 kB)\n","\u001b[K     |████████████████████████████████| 122 kB 5.8 MB/s \n","\u001b[?25hRequirement already satisfied: importlib-metadata<5 in /usr/local/lib/python3.7/dist-packages (from ipykernel) (4.6.4)\n","Requirement already satisfied: tornado<7.0,>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipykernel) (5.1.1)\n","Requirement already satisfied: debugpy<2.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel) (1.0.0)\n","Requirement already satisfied: jupyter-client<8.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel) (5.3.5)\n","Collecting ipython<8.0,>=7.23.1\n","  Downloading ipython-7.27.0-py3-none-any.whl (787 kB)\n","\u001b[K     |████████████████████████████████| 787 kB 28.7 MB/s \n","\u001b[?25hRequirement already satisfied: traitlets<6.0,>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel) (5.0.5)\n","Requirement already satisfied: matplotlib-inline<0.2.0,>=0.1.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel) (0.1.2)\n","Requirement already satisfied: argcomplete>=1.12.3 in /usr/local/lib/python3.7/dist-packages (from ipykernel) (1.12.3)\n","Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata<5->ipykernel) (3.5.0)\n","Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata<5->ipykernel) (3.7.4.3)\n","Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0\n","  Downloading prompt_toolkit-3.0.20-py3-none-any.whl (370 kB)\n","\u001b[K     |████████████████████████████████| 370 kB 51.6 MB/s \n","\u001b[?25hRequirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython<8.0,>=7.23.1->ipykernel) (2.6.1)\n","Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.7/dist-packages (from ipython<8.0,>=7.23.1->ipykernel) (4.8.0)\n","Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython<8.0,>=7.23.1->ipykernel) (0.7.5)\n","Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython<8.0,>=7.23.1->ipykernel) (4.4.2)\n","Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.7/dist-packages (from ipython<8.0,>=7.23.1->ipykernel) (0.18.0)\n","Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython<8.0,>=7.23.1->ipykernel) (57.4.0)\n","Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython<8.0,>=7.23.1->ipykernel) (0.2.0)\n","Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.16->ipython<8.0,>=7.23.1->ipykernel) (0.8.2)\n","Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel) (4.7.1)\n","Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel) (22.2.1)\n","Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel) (2.8.2)\n","Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect>4.3->ipython<8.0,>=7.23.1->ipykernel) (0.7.0)\n","Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython<8.0,>=7.23.1->ipykernel) (0.2.5)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->jupyter-client<8.0->ipykernel) (1.15.0)\n","Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/dist-packages (from traitlets<6.0,>=4.1.0->ipykernel) (0.2.0)\n","Installing collected packages: prompt-toolkit, ipython, ipykernel\n","  Attempting uninstall: prompt-toolkit\n","    Found existing installation: prompt-toolkit 1.0.18\n","    Uninstalling prompt-toolkit-1.0.18:\n","      Successfully uninstalled prompt-toolkit-1.0.18\n","  Attempting uninstall: ipython\n","    Found existing installation: ipython 5.5.0\n","    Uninstalling ipython-5.5.0:\n","      Successfully uninstalled ipython-5.5.0\n","  Attempting uninstall: ipykernel\n","    Found existing installation: ipykernel 4.10.1\n","    Uninstalling ipykernel-4.10.1:\n","      Successfully uninstalled ipykernel-4.10.1\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","jupyter-console 5.2.0 requires prompt-toolkit<2.0.0,>=1.0.0, but you have prompt-toolkit 3.0.20 which is incompatible.\n","google-colab 1.0.0 requires ipykernel~=4.10, but you have ipykernel 6.2.0 which is incompatible.\n","google-colab 1.0.0 requires ipython~=5.5.0, but you have ipython 7.27.0 which is incompatible.\u001b[0m\n","Successfully installed ipykernel-6.2.0 ipython-7.27.0 prompt-toolkit-3.0.20\n"],"name":"stdout"},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["IPython","ipykernel","prompt_toolkit"]}}},"metadata":{}},{"output_type":"stream","text":["Collecting modin[dask]\n","  Downloading modin-0.10.2-py3-none-manylinux1_x86_64.whl (715 kB)\n","\u001b[K     |████████████████████████████████| 715 kB 5.2 MB/s \n","\u001b[?25hCollecting pandas==1.3.2\n","  Downloading pandas-1.3.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)\n","\u001b[K     |████████████████████████████████| 11.3 MB 41.5 MB/s \n","\u001b[?25hRequirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.7/dist-packages (from modin[dask]) (1.19.5)\n","Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from modin[dask]) (21.0)\n","Collecting dask>=2.22.0\n","  Downloading dask-2021.8.1-py3-none-any.whl (1.0 MB)\n","\u001b[K     |████████████████████████████████| 1.0 MB 42.7 MB/s \n","\u001b[?25hCollecting distributed>=2.22.0\n","  Downloading distributed-2021.8.1-py3-none-any.whl (778 kB)\n","\u001b[K     |████████████████████████████████| 778 kB 54.8 MB/s \n","\u001b[?25hRequirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.3.2->modin[dask]) (2.8.2)\n","Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.3.2->modin[dask]) (2018.9)\n","Requirement already satisfied: toolz>=0.8.2 in /usr/local/lib/python3.7/dist-packages (from dask>=2.22.0->modin[dask]) (0.11.1)\n","Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from dask>=2.22.0->modin[dask]) (3.13)\n","Collecting partd>=0.3.10\n","  Downloading partd-1.2.0-py3-none-any.whl (19 kB)\n","Requirement already satisfied: cloudpickle>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from dask>=2.22.0->modin[dask]) (1.3.0)\n","Collecting fsspec>=0.6.0\n","  Downloading fsspec-2021.7.0-py3-none-any.whl (118 kB)\n","\u001b[K     |████████████████████████████████| 118 kB 60.4 MB/s \n","\u001b[?25hRequirement already satisfied: zict>=0.1.3 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.22.0->modin[dask]) (2.0.0)\n","Requirement already satisfied: tornado>=5 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.22.0->modin[dask]) (5.1.1)\n","Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.22.0->modin[dask]) (1.7.0)\n","Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.22.0->modin[dask]) (2.11.3)\n","Requirement already satisfied: click>=6.6 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.22.0->modin[dask]) (7.1.2)\n","Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.22.0->modin[dask]) (2.4.0)\n","Requirement already satisfied: msgpack>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.22.0->modin[dask]) (1.0.2)\n","Requirement already satisfied: psutil>=5.0 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.22.0->modin[dask]) (5.4.8)\n","Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from distributed>=2.22.0->modin[dask]) (57.4.0)\n","Collecting cloudpickle>=1.1.1\n","  Downloading cloudpickle-1.6.0-py3-none-any.whl (23 kB)\n","Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->modin[dask]) (2.4.7)\n","Collecting locket\n","  Downloading locket-0.2.1-py2.py3-none-any.whl (4.1 kB)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas==1.3.2->modin[dask]) (1.15.0)\n","Requirement already satisfied: heapdict in /usr/local/lib/python3.7/dist-packages (from zict>=0.1.3->distributed>=2.22.0->modin[dask]) (1.0.1)\n","Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->distributed>=2.22.0->modin[dask]) (2.0.1)\n","Installing collected packages: locket, partd, fsspec, cloudpickle, pandas, dask, modin, distributed\n","  Attempting uninstall: cloudpickle\n","    Found existing installation: cloudpickle 1.3.0\n","    Uninstalling cloudpickle-1.3.0:\n","      Successfully uninstalled cloudpickle-1.3.0\n","  Attempting uninstall: pandas\n","    Found existing installation: pandas 1.1.5\n","    Uninstalling pandas-1.1.5:\n","      Successfully uninstalled pandas-1.1.5\n","  Attempting uninstall: dask\n","    Found existing installation: dask 2.12.0\n","    Uninstalling dask-2.12.0:\n","      Successfully uninstalled dask-2.12.0\n","  Attempting uninstall: distributed\n","    Found existing installation: distributed 1.25.3\n","    Uninstalling distributed-1.25.3:\n","      Successfully uninstalled distributed-1.25.3\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","google-colab 1.0.0 requires ipykernel~=4.10, but you have ipykernel 6.2.0 which is incompatible.\n","google-colab 1.0.0 requires ipython~=5.5.0, but you have ipython 7.27.0 which is incompatible.\n","google-colab 1.0.0 requires pandas~=1.1.0; python_version >= \"3.0\", but you have pandas 1.3.2 which is incompatible.\u001b[0m\n","Successfully installed cloudpickle-1.6.0 dask-2021.8.1 distributed-2021.8.1 fsspec-2021.7.0 locket-0.2.1 modin-0.10.2 pandas-1.3.2 partd-1.2.0\n"],"name":"stdout"},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["pandas"]}}},"metadata":{}},{"output_type":"stream","text":["Requirement already satisfied: modin[ray] in /usr/local/lib/python3.7/dist-packages (0.10.2)\n","Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.7/dist-packages (from modin[ray]) (1.19.5)\n","Requirement already satisfied: pandas==1.3.2 in /usr/local/lib/python3.7/dist-packages (from modin[ray]) (1.3.2)\n","Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from modin[ray]) (21.0)\n","Collecting pyarrow>=1.0\n","  Downloading pyarrow-5.0.0-cp37-cp37m-manylinux2014_x86_64.whl (23.6 MB)\n","\u001b[K     |████████████████████████████████| 23.6 MB 124 kB/s \n","\u001b[?25hCollecting ray[default]>=1.4.0\n","  Downloading ray-1.6.0-cp37-cp37m-manylinux2014_x86_64.whl (49.6 MB)\n","\u001b[K     |████████████████████████████████| 49.6 MB 6.0 kB/s \n","\u001b[?25hRequirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.3.2->modin[ray]) (2018.9)\n","Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.3.2->modin[ray]) (2.8.2)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas==1.3.2->modin[ray]) (1.15.0)\n","Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (3.0.12)\n","Requirement already satisfied: protobuf>=3.15.3 in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (3.17.3)\n","Requirement already satisfied: attrs in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (21.2.0)\n","Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (3.13)\n","Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (7.1.2)\n","Requirement already satisfied: redis>=3.5.0 in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (3.5.3)\n","Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (1.0.2)\n","Requirement already satisfied: grpcio>=1.28.1 in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (1.39.0)\n","Collecting colorful\n","  Downloading colorful-0.5.4-py2.py3-none-any.whl (201 kB)\n","\u001b[K     |████████████████████████████████| 201 kB 55.1 MB/s \n","\u001b[?25hCollecting aiohttp\n","  Downloading aiohttp-3.7.4.post0-cp37-cp37m-manylinux2014_x86_64.whl (1.3 MB)\n","\u001b[K     |████████████████████████████████| 1.3 MB 53.0 MB/s \n","\u001b[?25hRequirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (2.23.0)\n","Collecting aioredis<2\n","  Downloading aioredis-1.3.1-py3-none-any.whl (65 kB)\n","\u001b[K     |████████████████████████████████| 65 kB 3.5 MB/s \n","\u001b[?25hCollecting aiohttp-cors\n","  Downloading aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)\n","Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (2.6.0)\n","Collecting gpustat\n","  Downloading gpustat-0.6.0.tar.gz (78 kB)\n","\u001b[K     |████████████████████████████████| 78 kB 4.6 MB/s \n","\u001b[?25hRequirement already satisfied: prometheus-client>=0.7.1 in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (0.11.0)\n","Requirement already satisfied: py-spy>=0.2.0 in /usr/local/lib/python3.7/dist-packages (from ray[default]>=1.4.0->modin[ray]) (0.3.8)\n","Collecting opencensus\n","  Downloading opencensus-0.7.13-py2.py3-none-any.whl (127 kB)\n","\u001b[K     |████████████████████████████████| 127 kB 51.0 MB/s \n","\u001b[?25hCollecting async-timeout\n","  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)\n","Collecting hiredis\n","  Downloading hiredis-2.0.0-cp37-cp37m-manylinux2010_x86_64.whl (85 kB)\n","\u001b[K     |████████████████████████████████| 85 kB 3.4 MB/s \n","\u001b[?25hRequirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp->ray[default]>=1.4.0->modin[ray]) (3.7.4.3)\n","Collecting yarl<2.0,>=1.0\n","  Downloading yarl-1.6.3-cp37-cp37m-manylinux2014_x86_64.whl (294 kB)\n","\u001b[K     |████████████████████████████████| 294 kB 45.1 MB/s \n","\u001b[?25hRequirement already satisfied: chardet<5.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->ray[default]>=1.4.0->modin[ray]) (3.0.4)\n","Collecting multidict<7.0,>=4.5\n","  Downloading multidict-5.1.0-cp37-cp37m-manylinux2014_x86_64.whl (142 kB)\n","\u001b[K     |████████████████████████████████| 142 kB 54.1 MB/s \n","\u001b[?25hRequirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/dist-packages (from yarl<2.0,>=1.0->aiohttp->ray[default]>=1.4.0->modin[ray]) (2.10)\n","Requirement already satisfied: nvidia-ml-py3>=7.352.0 in /usr/local/lib/python3.7/dist-packages (from gpustat->ray[default]>=1.4.0->modin[ray]) (7.352.0)\n","Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from gpustat->ray[default]>=1.4.0->modin[ray]) (5.4.8)\n","Collecting blessings>=1.6\n","  Downloading blessings-1.7-py3-none-any.whl (18 kB)\n","Collecting opencensus-context==0.1.2\n","  Downloading opencensus_context-0.1.2-py2.py3-none-any.whl (4.4 kB)\n","Requirement already satisfied: google-api-core<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from opencensus->ray[default]>=1.4.0->modin[ray]) (1.26.3)\n","Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core<2.0.0,>=1.0.0->opencensus->ray[default]>=1.4.0->modin[ray]) (57.4.0)\n","Requirement already satisfied: google-auth<2.0dev,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from google-api-core<2.0.0,>=1.0.0->opencensus->ray[default]>=1.4.0->modin[ray]) (1.34.0)\n","Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core<2.0.0,>=1.0.0->opencensus->ray[default]>=1.4.0->modin[ray]) (1.53.0)\n","Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.21.1->google-api-core<2.0.0,>=1.0.0->opencensus->ray[default]>=1.4.0->modin[ray]) (0.2.8)\n","Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.21.1->google-api-core<2.0.0,>=1.0.0->opencensus->ray[default]>=1.4.0->modin[ray]) (4.7.2)\n","Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<2.0dev,>=1.21.1->google-api-core<2.0.0,>=1.0.0->opencensus->ray[default]>=1.4.0->modin[ray]) (4.2.2)\n","Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->modin[ray]) (2.4.7)\n","Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.21.1->google-api-core<2.0.0,>=1.0.0->opencensus->ray[default]>=1.4.0->modin[ray]) (0.4.8)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->ray[default]>=1.4.0->modin[ray]) (2021.5.30)\n","Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->ray[default]>=1.4.0->modin[ray]) (1.24.3)\n","Building wheels for collected packages: gpustat\n","  Building wheel for gpustat (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for gpustat: filename=gpustat-0.6.0-py3-none-any.whl size=12617 sha256=96b7aebe6bcc269e1208945aa28e173de3d80b8c25d01f67d3d8508b4fdf8177\n","  Stored in directory: /root/.cache/pip/wheels/e6/67/af/f1ad15974b8fd95f59a63dbf854483ebe5c7a46a93930798b8\n","Successfully built gpustat\n","Installing collected packages: multidict, yarl, async-timeout, opencensus-context, hiredis, blessings, aiohttp, ray, opencensus, gpustat, colorful, aioredis, aiohttp-cors, pyarrow\n","  Attempting uninstall: ray\n","    Found existing installation: ray 0.7.5\n","    Uninstalling ray-0.7.5:\n","      Successfully uninstalled ray-0.7.5\n","Successfully installed aiohttp-3.7.4.post0 aiohttp-cors-0.7.0 aioredis-1.3.1 async-timeout-3.0.1 blessings-1.7 colorful-0.5.4 gpustat-0.6.0 hiredis-2.0.0 multidict-5.1.0 opencensus-0.7.13 opencensus-context-0.1.2 pyarrow-5.0.0 ray-1.6.0 yarl-1.6.3\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"L12inyOaw6yd"},"source":["import pandas as pd\n","import dask\n","import dask.dataframe as dd\n","import modin.pandas as md\n","import ray\n","#import ray.dataframe as rd\n","import time\n","import yaml\n","import json"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"jdWNQba20HGf","executionInfo":{"status":"ok","timestamp":1630167869858,"user_tz":240,"elapsed":913,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}}},"source":["import pandas as pd\n","import dask\n","import dask.dataframe as dd\n","import yaml\n","import time\n","import json"],"execution_count":2,"outputs":[]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"3SoQbeSd0scE","executionInfo":{"status":"ok","timestamp":1630169302108,"user_tz":240,"elapsed":116,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}},"outputId":"de66e652-b070-46f4-91a7-3434e870d753"},"source":["from google.colab import drive\n","drive.mount('/content/gdrive')\n","file_path = '/content/gdrive/My Drive/Data_Glacier/Week_6/statements.csv'"],"execution_count":1,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount(\"/content/gdrive\", force_remount=True).\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"OAnc06Dk1Ndq","executionInfo":{"status":"ok","timestamp":1630167471280,"user_tz":240,"elapsed":721,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}},"outputId":"be2cb77d-2059-48e8-fda6-e2bf8606bc70"},"source":["#time taken by dask\n","tic = time.time()\n","df = dd.read_csv(file_path)\n","toc = time.time()\n","print(toc-tic)"],"execution_count":3,"outputs":[{"output_type":"stream","text":["0.666628360748291\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"09mOsImT2pmz","executionInfo":{"status":"ok","timestamp":1629753700575,"user_tz":240,"elapsed":71166,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}},"outputId":"c0f08195-1f82-4d6e-fcc9-40ff4c127499"},"source":["#time taken by modin\n","ray.shutdown()\n","ray.init()\n","tic = time.time()\n","df = md.read_csv(file_path)\n","toc = time.time()\n","print(toc-tic)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["2021-08-23 21:20:32,005\tINFO services.py:1265 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n","2021-08-23 21:20:35,209\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","2021-08-23 21:20:38,949\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","2021-08-23 21:20:42,694\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[36m(pid=1115)\u001b[0m tcmalloc: large alloc 1316298752 bytes == 0x5623a994e000 @  0x7f887d3d61e7 0x5623a6c71a18 0x5623a6c3c987 0x5623a6d1e6be 0x5623a6c3fea9 0x5623a6d31c0d 0x5623a6cb40d8 0x5623a6caec35 0x5623a6b80e2c 0x5623a6cb1318 0x5623a6b80d14 0x7f887a200f22 0x7f887a2a7916 0x7f887a2074c5 0x7f887a36ec06 0x7f887a2eb652 0x7f887a38ba25 0x7f887a38c48a 0x7f887a30db35 0x7f887a6cb5e6 0x7f887a7cde58 0x7f887a7cea11 0x7f887a7d0560 0x7f887a378405 0x7f887a2033d7 0x5623a6c3ff01 0x5623a6d31c0d 0x5623a6cb40d8 0x5623a6c4165a 0x5623a6cafd67 0x5623a6caec35\n","\u001b[2m\u001b[36m(pid=1114)\u001b[0m tcmalloc: large alloc 1316298752 bytes == 0x55563d9a8000 @  0x7f98799411e7 0x555639c77a18 0x555639c42987 0x555639d246be 0x555639c45ea9 0x555639d37c0d 0x555639cba0d8 0x555639cb4c35 0x555639b86e2c 0x555639cb7318 0x555639b86d14 0x7f987676bf22 0x7f9876812916 0x7f98767724c5 0x7f98768d9c06 0x7f9876856652 0x7f98768f6a25 0x7f98768f748a 0x7f9876878b35 0x7f9876c365e6 0x7f9876d38e58 0x7f9876d39a11 0x7f9876d3b560 0x7f98768e3405 0x7f987676e3d7 0x555639c45f01 0x555639d37c0d 0x555639cba0d8 0x555639c4765a 0x555639cb5d67 0x555639cb4c35\n","2021-08-23 21:20:45,923\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","\u001b[2m\u001b[36m(pid=1115)\u001b[0m tcmalloc: large alloc 1316298752 bytes == 0x5623f80d2000 @  0x7f887d3d61e7 0x5623a6c71a18 0x5623a6c3cbbc 0x5623a6cb0526 0x5623a6caec35 0x5623a6b80e2c 0x5623a6cb1318 0x5623a6b80d14 0x7f887a200f22 0x7f887a2a7916 0x7f887a2074c5 0x7f887a36ec06 0x7f887a2eb652 0x7f887a38ba25 0x7f887a38c48a 0x7f887a30db35 0x7f887a6cb5e6 0x7f887a7cde58 0x7f887a7cea11 0x7f887a7d0560 0x7f887a378405 0x7f887a2033d7 0x5623a6c3ff01 0x5623a6d31c0d 0x5623a6cb40d8 0x5623a6c4165a 0x5623a6cafd67 0x5623a6caec35 0x5623a6cae933 0x5623a6d78402 0x5623a6d7877d\n","\u001b[2m\u001b[36m(pid=1114)\u001b[0m tcmalloc: large alloc 1316298752 bytes == 0x55568c138000 @  0x7f98799411e7 0x555639c77a18 0x555639c42bbc 0x555639cb6526 0x555639cb4c35 0x555639b86e2c 0x555639cb7318 0x555639b86d14 0x7f987676bf22 0x7f9876812916 0x7f98767724c5 0x7f98768d9c06 0x7f9876856652 0x7f98768f6a25 0x7f98768f748a 0x7f9876878b35 0x7f9876c365e6 0x7f9876d38e58 0x7f9876d39a11 0x7f9876d3b560 0x7f98768e3405 0x7f987676e3d7 0x555639c45f01 0x555639d37c0d 0x555639cba0d8 0x555639c4765a 0x555639cb5d67 0x555639cb4c35 0x555639cb4933 0x555639d7e402 0x555639d7e77d\n","2021-08-23 21:20:51,563\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","2021-08-23 21:20:55,959\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","2021-08-23 21:21:00,305\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","2021-08-23 21:21:04,574\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","2021-08-23 21:21:09,010\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","2021-08-23 21:21:13,222\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","2021-08-23 21:21:17,498\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","2021-08-23 21:21:22,082\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","2021-08-23 21:21:26,277\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","\u001b[2m\u001b[36m(pid=1114)\u001b[0m tcmalloc: large alloc 1642561536 bytes == 0x555752e58000 @  0x7f98799411e7 0x7f9873a9246e 0x7f9873ae2c7b 0x7f9873ae335f 0x7f9873b85103 0x555639c460a4 0x555639c45da0 0x555639cba868 0x555639c4765a 0x555639cb5b0e 0x555639cb4c35 0x555639c4773a 0x555639cb693b 0x555639c4765a 0x555639cb5b0e 0x555639cb4c35 0x555639c4773a 0x555639cb693b 0x555639cb5235 0x555639c4773a 0x555639cb693b 0x555639cb5235 0x555639c4773a 0x555639cb693b 0x555639cb5235 0x555639c47fec 0x555639c88bc9 0x555639c85ac4 0x555639c468a9 0x555639cbab0a 0x555639cb4c35\n","2021-08-23 21:21:31,877\tWARNING worker.py:1215 -- The agent on node 1dfc406f73a7 failed with the following error:\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","    loop.run_until_complete(agent.run())\n","  File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","    return future.result()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","    modules = self._load_modules()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","    c = cls(self)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","    namespace=\"ray\", port=metrics_export_port)))\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","    options=option, gatherer=option.registry, collector=collector)\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","    self.serve_http()\n","  File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","    port=self.options.port, addr=str(self.options.address))\n","  File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","    server = server_class((host, port), handler_class)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","    self.server_bind()\n","  File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","    HTTPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","    socketserver.TCPServer.server_bind(self)\n","  File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","    self.socket.bind(self.server_address)\n","OSError: [Errno 98] Address already in use\n","\n","\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 382, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 370, in <module>\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/asyncio/base_events.py\", line 587, in run_until_complete\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 151, in run\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py\", line 105, in _load_modules\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 153, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py\", line 149, in start_wsgi_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 153, in make_server\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     server = server_class((host, port), handler_class)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 452, in __init__\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.server_bind()\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/wsgiref/simple_server.py\", line 50, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     HTTPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/http/server.py\", line 137, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     socketserver.TCPServer.server_bind(self)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/usr/lib/python3.7/socketserver.py\", line 466, in server_bind\n","\u001b[2m\u001b[33m(raylet)\u001b[0m     self.socket.bind(self.server_address)\n","\u001b[2m\u001b[33m(raylet)\u001b[0m OSError: [Errno 98] Address already in use\n","\u001b[2m\u001b[36m(pid=1115)\u001b[0m tcmalloc: large alloc 1746411520 bytes == 0x5624cb236000 @  0x7f887d3d61e7 0x7f887752746e 0x7f8877577c7b 0x7f887757835f 0x7f887761a103 0x5623a6c400a4 0x5623a6c3fda0 0x5623a6cb4868 0x5623a6c4165a 0x5623a6cafb0e 0x5623a6caec35 0x5623a6c4173a 0x5623a6cb093b 0x5623a6c4165a 0x5623a6cafb0e 0x5623a6caec35 0x5623a6c4173a 0x5623a6cb093b 0x5623a6caf235 0x5623a6c4173a 0x5623a6cb093b 0x5623a6caf235 0x5623a6c4173a 0x5623a6cb093b 0x5623a6caf235 0x5623a6c41fec 0x5623a6c82bc9 0x5623a6c7fac4 0x5623a6c408a9 0x5623a6cb4b0a 0x5623a6caec35\n"],"name":"stderr"},{"output_type":"stream","text":["66.04646921157837\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"SpWgSxNL5LT0","executionInfo":{"status":"ok","timestamp":1629998620583,"user_tz":240,"elapsed":59737,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}},"outputId":"08976adb-ecbf-4a35-a568-d40ed76a86b4"},"source":["#time taken by pandas\n","tic = time.time()\n","df = pd.read_csv(file_path)\n","toc = time.time()\n","print(toc-tic)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["tcmalloc: large alloc 1129660416 bytes == 0x55f1aaecc000 @  0x7f5b664581e7 0x7f5b5d1ce46e 0x7f5b5d21ec7b 0x7f5b5d21ed18 0x7f5b5d2c6010 0x7f5b5d2c673c 0x7f5b5d2c685d 0x55f0da0a32b8 0x7f5b5d20bef7 0x55f0da0a0f97 0x55f0da0a0da0 0x55f0da114bb3 0x55f0da10fc35 0x55f0da0a273a 0x55f0da114f40 0x55f0da110235 0x55f0da0a273a 0x55f0da110b0e 0x55f0da110235 0x55f0da0a273a 0x55f0da110d67 0x55f0da10fc35 0x55f0da0a273a 0x55f0da110d67 0x55f0da0a265a 0x55f0da110b0e 0x55f0da10fc35 0x55f0d9fe1eb1 0x55f0da112318 0x55f0da110235 0x55f0da0a273a\n","tcmalloc: large alloc 3388964864 bytes == 0x55f274ec8000 @  0x7f5b664581e7 0x7f5b5d1ce46e 0x7f5b5d21ec7b 0x7f5b5d21f35f 0x7f5b5d2c1103 0x55f0da0a10a4 0x55f0da0a0da0 0x55f0da115868 0x55f0da0a265a 0x55f0da110b0e 0x55f0da10fc35 0x55f0da0a273a 0x55f0da11193b 0x55f0da0a265a 0x55f0da110b0e 0x55f0da10fc35 0x55f0da0a273a 0x55f0da11193b 0x55f0da110235 0x55f0da0a273a 0x55f0da11193b 0x55f0da110235 0x55f0da0a273a 0x55f0da11193b 0x55f0da110235 0x55f0da0a2fec 0x55f0da0e3bc9 0x55f0da0e0ac4 0x55f0da0a18a9 0x55f0da115b0a 0x55f0da10fc35\n"],"name":"stderr"},{"output_type":"stream","text":["59.545974254608154\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"trME1Tyf59Te","executionInfo":{"status":"ok","timestamp":1630167471991,"user_tz":240,"elapsed":122,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}},"outputId":"ae912a1f-1662-4fa4-a887-cfdb43b77fa1"},"source":["df.columns=df.columns.str.replace('[#,@,&,^,*,<,>]','')\n","df.columns=df.columns.str.strip()\n","df.columns = df.columns.str.replace(' ', '_')"],"execution_count":4,"outputs":[{"output_type":"stream","text":["/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.\n","  \"\"\"Entry point for launching an IPython kernel.\n"],"name":"stderr"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"EoelBZnn9kaq","executionInfo":{"status":"ok","timestamp":1630167473647,"user_tz":240,"elapsed":153,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}},"outputId":"cb6b2bb3-3208-4221-d813-62f36531f4ad"},"source":["df.columns"],"execution_count":5,"outputs":[{"output_type":"execute_result","data":{"text/plain":["Index(['source_item_id', 'edge_property_id', 'target_item_id'], dtype='object')"]},"metadata":{},"execution_count":5}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":206},"id":"o8I8AVz95lTZ","executionInfo":{"status":"ok","timestamp":1630167477631,"user_tz":240,"elapsed":2088,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}},"outputId":"8786c6f0-e4df-492f-e198-20735060fc2b"},"source":["df.head()"],"execution_count":6,"outputs":[{"output_type":"execute_result","data":{"text/html":["<div>\n","<style scoped>\n","    .dataframe tbody tr th:only-of-type {\n","        vertical-align: middle;\n","    }\n","\n","    .dataframe tbody tr th {\n","        vertical-align: top;\n","    }\n","\n","    .dataframe thead th {\n","        text-align: right;\n","    }\n","</style>\n","<table border=\"1\" class=\"dataframe\">\n","  <thead>\n","    <tr style=\"text-align: right;\">\n","      <th></th>\n","      <th>source_item_id</th>\n","      <th>edge_property_id</th>\n","      <th>target_item_id</th>\n","    </tr>\n","  </thead>\n","  <tbody>\n","    <tr>\n","      <th>0</th>\n","      <td>1</td>\n","      <td>31</td>\n","      <td>36906466</td>\n","    </tr>\n","    <tr>\n","      <th>1</th>\n","      <td>1</td>\n","      <td>279</td>\n","      <td>3695190</td>\n","    </tr>\n","    <tr>\n","      <th>2</th>\n","      <td>1</td>\n","      <td>398</td>\n","      <td>497745</td>\n","    </tr>\n","    <tr>\n","      <th>3</th>\n","      <td>1</td>\n","      <td>398</td>\n","      <td>1133705</td>\n","    </tr>\n","    <tr>\n","      <th>4</th>\n","      <td>1</td>\n","      <td>398</td>\n","      <td>1139177</td>\n","    </tr>\n","  </tbody>\n","</table>\n","</div>"],"text/plain":["   source_item_id  edge_property_id  target_item_id\n","0               1                31        36906466\n","1               1               279         3695190\n","2               1               398          497745\n","3               1               398         1133705\n","4               1               398         1139177"]},"metadata":{},"execution_count":6}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"9claxwXiRAxW","executionInfo":{"status":"ok","timestamp":1630167477634,"user_tz":240,"elapsed":28,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}},"outputId":"a2ffae9d-16cc-49e2-cc67-f1bd75572ec8"},"source":["df.shape"],"execution_count":7,"outputs":[{"output_type":"execute_result","data":{"text/plain":["(Delayed('int-6157acda-a112-4eec-ba5f-8c19213750c7'), 3)"]},"metadata":{},"execution_count":7}]},{"cell_type":"code","metadata":{"id":"AQ6B21f7bOh2"},"source":["json_file_path = ['/content/gdrive/My Drive/Data_Glacier/Week_6/data.json']\n","\n","parsed = dd.to_json(df, json_file_path, orient='index')"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"vm8sB5V6tHna","executionInfo":{"status":"ok","timestamp":1630167946747,"user_tz":240,"elapsed":8569,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}}},"source":["import json\n","import gzip\n","import yaml\n","\n","with open('/content/gdrive/My Drive/Data_Glacier/Week_6/data.json', 'r') as f:\n","  data = json.load(f)"],"execution_count":5,"outputs":[]},{"cell_type":"code","metadata":{"id":"d_moHaialFrs","executionInfo":{"status":"ok","timestamp":1630168328846,"user_tz":240,"elapsed":83769,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}}},"source":["with gzip.open('/content/gdrive/My Drive/Data_Glacier/Week_6/data.json.gz', 'wt', encoding='UTF-8') as zip:\n","  json.dump(data, zip)"],"execution_count":8,"outputs":[]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"3v-RKWZ_qOEv","executionInfo":{"status":"ok","timestamp":1630169505193,"user_tz":240,"elapsed":29749,"user":{"displayName":"Arhum Ahmad","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiXPf_rJJSigkT6k8ht8W-ioHB9kB4P1kIN_cUbcg=s64","userId":"04255844488172887258"}},"outputId":"f58958c8-631b-421d-d14c-530e0437b4f1"},"source":["import json, gzip, pandas\n","\n","filename = '/content/gdrive/My Drive/Data_Glacier/Week_6/data.json.gz'\n","with gzip.open(filename, 'r') as f:\n","  data = json.loads(f.read().decode('UTF-8'))\n","\n","data = pandas.DataFrame.from_dict(data, orient='index')\n","print(data.shape)"],"execution_count":4,"outputs":[{"output_type":"stream","text":["(3739666, 3)\n"],"name":"stdout"}]}]}